openwisp/django-freeradius

django_freeradius/admin.py, django_freeradius/base/models.py, django_freeradius/models.py, django_freeradius/tests/tests_admin.py, django_freeradius/tests/tests_models.py, runflake8, runisort, setup.cfg, tests/sample_radius/admin.py, tests/sample_radius/models.py, tests/sample_radius/tests.py
=> Configure isort / flake8 using setup.cfg

.travis.yml
=> [cleanup] Do not load mysql / postgres in the same configuration 

django_freeradius/api/urls.py, django_freeradius/api/views.py, django_freeradius/tests/test_api.py, django_freeradius/urls.py, requirements.txt, tests/settings.py, tests/urls.py
=> [api] Added authorize

django_freeradius/api/urls.py, django_freeradius/api/views.py, django_freeradius/tests/test_api.py, docs/source/general/freeradius.rst
=> Freeradius postauth

django_freeradius/api/serializers.py, django_freeradius/api/urls.py, django_freeradius/api/views.py, django_freeradius/tests/test_api.py, docs/source/general/freeradius.rst, requirements-test.txt
Implements and fixes #3 
Implements and fixes #38
=> [api] Added accounting view

django_freeradius/management/commands/delete_old_radacct.py, django_freeradius/tests/test_admin.py, docs/source/general/management_commands.rst, docs/source/index.rst
=> [management] Added command to delete sessions older than <days> #50

django_freeradius/management/commands/delete_old_postauth.py, django_freeradius/tests/test_admin.py, docs/source/general/management_commands.rst
=> [management] Added command to delete post-auth logs older than <days> #73

django_freeradius/management/commands/cleanup_stale_radacct.py, django_freeradius/tests/test_admin.py, django_freeradius/tests/test_commands.py, docs/source/general/management_commands.rst
=> [accounting] Added command to deal with unterminated radacct entries #47

docs/source/general/freeradius.rst
this will add links to the sql and rest documentation on the freeradius wiki
I also moved to the end of the "Configure Freeradius" section the commands to link files and restart freeradius as it should be done last.
=> better step by step subdivision

django_freeradius/api/views.py, django_freeradius/tests/base/test_api.py
=> [api] check if user is enabled before authorization #63

django_freeradius/api/serializers.py, django_freeradius/api/views.py, django_freeradius/tests/base/test_api.py
Fixes #69. 
I'm not actually totally sure this solves the problem but I wrote tests for it as well.
=> [api] Added accounting start request with missing fields

requirements-test.txt, tests/settings.py, tests/urls.py
Fix for - https://github.com/openwisp/django-freeradius/issues/96
=> Added openwisp admin theme to django-freeradius

requirements-test.txt
#94 I just changed few lines of code here and most of the work I think was already present there to support Django>2.0. @nemesisdesign or  @rohitasrk Please review this and tell me if this was fine! :)
=> #94 Changed travis.yml to support django>2.0

django_freeradius/api/views.py, django_freeradius/tests/base/test_api.py, requirements.txt, tests/settings.py
Implements and closes #99 
Also added django-crispy-forms for the DRF’s browsable API.
=> [api] Improved filtering #99

docs/source/general/freeradius.rst
more handholding but not too much, they can search for themselves
=> Explicitly state to configure the SQL server

docs/source/general/freeradius.rst
=> [docs] Added dev environment config instructions

docs/source/general/api.rst, docs/source/index.rst
Implements and closes #102
Use of automethod or autofunction didn't seem appropriate because we are going to document API endpoints and not functions, right ?
@nemesisdesign @rohithasrk please review it and suggest if any more content should be added or not. ?
=> [docs] Documented API usage

django_freeradius/base/models.py
=> Imported TimeStampedEditableModel from openwisp-utils

django_freeradius/base/forms.py, django_freeradius/management/commands/prefix_add_users.py, django_freeradius/tests/base/test_admin.py, django_freeradius/tests/base/test_commands.py
=> Added a MinValueValidator to number_of_users field on prefix generation

django_freeradius/static/django-freeradius/js/radcheck.js
This can be improved by adding an option to mask/hide the existing 
hash/password if set.
Fixes #127
=> [radcheck.js] Don't hide newValueRow if value not set #127

django_freeradius/management/commands/batch_add_users.py, django_freeradius/management/commands/cleanup_stale_radacct.py, django_freeradius/management/commands/deactivate_expired_users.py, django_freeradius/management/commands/delete_old_postauth.py, django_freeradius/management/commands/delete_old_radacct.py, django_freeradius/management/commands/delete_old_users.py, django_freeradius/management/commands/prefix_add_users.py, tests/sample_radius/tests.py
Fixes #119 
Sorry for the resend
=> reused tests in sample_radius/tests.py.

django_freeradius/base/admin.py, django_freeradius/tests/base/test_admin.py, django_freeradius/tests/test_admin.py, tests/sample_radius/tests.py
=> [admin] Added more info in RadiusProfileAdmin list view.

django_freeradius/api/views.py, django_freeradius/apps.py, django_freeradius/settings.py, django_freeradius/tests/base/test_api.py, docs/source/general/api.rst, docs/source/general/freeradius.rst, tests/settings.py
=> Token based authentication for the API

docs/source/general/freeradius.rst
This commit documents Django-Freeradius' support for Freeradius 
compatible password hashing and storage.
Documents #128
=> [docs] Document using Radius Checks for authorization

django_freeradius/urls.py, docs/source/general/api.rst, docs/source/general/freeradius.rst
=> [api] Versioned the API to v1

.travis.yml, django_freeradius/api/views.py, requirements.txt
=> [requirements] Upgraded to django-filter 2.0.0 #150

django_freeradius/base/models.py, django_freeradius/tests/base/test_api.py, django_freeradius/tests/base/test_models.py, django_freeradius/utils.py
=> Removed files related to batch user creation on deletion and changed filepaths

.travis.yml, requirements-test.txt
Officially support django 2.1 + travis build cleanup.
=> [django-2.1] Officially support django 2.1 + travis build cleanup

django_freeradius/static/django-freeradius/js/radcheck.js
[Bug Fix] Radius Check Form
radcheck.js modified for making sure that only password field values are hidden in add radiuscheck form.
The "Max-Daily-Session", "Max-All-Session", "Max-Daily-Session-Traffic" attribute values are not hidden.
Fixes #134
=> [Models] Radius Check Form Bug Fix

django_freeradius/base/models.py, django_freeradius/migrations/0002_create_default_radius_profiles.py
Added units in 'help_text'
Fixes #170
=> [#170][limits] Make units explicit

.travis.yml, setup.py
=> Updating python version in setup.py

.travis.yml, docs/source/general/registration.rst, docs/source/index.rst, requirements-test.txt, requirements.txt, tests/settings.py, tests/urls.py
Added registration recommendations.
=> Registration

django_freeradius/api/views.py
Fixes https://github.com/openwisp/openwisp-radius/issues/20.
=> Fixed [invalid name] field in AccountingView's filter_class

django_freeradius/base/forms.py, django_freeradius/tests/base/test_admin.py
Some admin tests were not good enough to spot errors.
Now these tests should fail if the right conditions arise.
Related to  #186  #202
=> [qa] Improved robustness of admin tests #186

.travis.yml
=> [qa] Added commit message style check #215

requirements.txt
Updated `openwisp-utils>=0.2,<0.3` to `openwisp-utils>=0.2,<0.3.1`
=> [requirements] Update openwisp-utils

django_freeradius/base/admin.py
=> [qa] Move ReadOnlyAdmin to openwisp-utils #201

docs/source/general/freeradius.rst
=> Update documentation for configuring Freeradius

.travis.yml, django_freeradius/base/admin.py, django_freeradius/base/forms.py, django_freeradius/tests/base/test_admin.py, requirements-test.txt
=> [django] Add support for django 2.2 #231

django_freeradius/base/admin.py, django_freeradius/tests/base/test_admin.py
=> [django] Improve support for django 2.2 #231

.travis.yml, requirements.txt
Made clear django 2.2 is supported.
=> [requirements] Made clear django 2.2 is supported

django_freeradius/base/forms.py, django_freeradius/base/models.py, django_freeradius/tests/base/test_batch_add_users.py, django_freeradius/tests/base/test_commands.py, django_freeradius/tests/static/test_batch.csv, django_freeradius/tests/static/test_batch_new.csv
=> [bug] Fix failing tests in openwisp_radius #236

django_freeradius/api/urls.py, django_freeradius/api/views.py, django_freeradius/tests/base/test_api.py, django_freeradius/tests/test_api.py
=> [api] Add API endpoint to validate user token #238

.travis.yml, django_freeradius/api/serializers.py, django_freeradius/base/models.py, django_freeradius/base/validators.py, django_freeradius/migrations/0001_initial_freeradius.py, django_freeradius/tests/base/test_api.py, django_freeradius/tests/base/test_models.py, tests/sample_radius/migrations/0001_initial.py
Added new fields from Freeradius server (3.0.20)
Closes #244
=> Add freeradius-server-3.0.19 db fields #244

.travis.yml, django_freeradius/api/urls.py, django_freeradius/base/admin.py, django_freeradius/tests/test_api.py, django_freeradius/tests/test_commands.py, requirements-test.txt, requirements.txt, setup.py
Updated dependencies
Testing on python version 3.6 and 3.7
Added Support for django 3
Closes #246
=> [requirements] Update dependencies & python version used. #246

docs/source/general/contributing.rst, docs/source/general/setup.rst
=> [docs] Improved installation documentation #253
