openwisp/django-freeradius

LICENSE

As discussed, I propose to switch the license of this project to GPLv3 for consistency with other critical OpenWISP modules (eg: openwisp-controller, netjsonconfig and the good old OpenWISP1 modules).
@yakky @lillopaco

[license] Switch to GPLv3

---

README.rst
docs/source/general/freeradius.rst
docs/source/general/setup.rst

`anom@ubuntu:~/django-freeradius$ python3 setup.py develop`
The following error occurred while trying to add or remove files in the
installation directory:
[Errno 13] Permission denied: '/usr/local/lib/python3.5/dist-packages/test-easy-install-95996.pth'
...
Perhaps your account does not have write access to this directory?  If the
installation directory is a system-owned directory, you may need to sign in
as the administrator or "root" account.  If you do not have administrative
access to this machine, you may wish to choose a different installation
directory, preferably one that is listed in your PYTHONPATH environment
variable.
So for fixing that I had to use `sudo` (*sudo python3 setup.py develop*)
After `pip3 install -r requirements-test.txt` I have got a lot of problems of …

[docs] Improve installation instructions

---

docs/source/general/freeradius.rst

this will change all the configuration files path to the one that
ships with debian stretch. I added a note for users with other distro
or version.
Also fixed a sphinx build error with using ~ instead of ^ for
subsubparagraphs

change configuration files path to debian defaults

---

django_freeradius/base/forms.py
django_freeradius/tests/base/test_admin.py

Using the help_text as "Refer to the [docs](https://django-freeradius.readthedocs.io/en/latest/general/importing_users.html) for more details on importing users from a CSV".

[admin] Add link to CSV import docs

---

django_freeradius/tests/base/test_models.py
django_freeradius/tests/test_api.py
django_freeradius/tests/test_models.py
django_freeradius/tests/test_utils.py
tests/sample_radius/tests.py

[tests] Added the missing tests to sample_radius

---

django_freeradius/tests/base/test_api.py
django_freeradius/tests/test_api.py
tests/sample_radius/tests.py

For openwisp-radius's tests, there needs to be a dynamic value for ```auth_header``` and this allows for it as the ```auth_header``` is set when the tests are inherited and run.

[api] Made auth_header in test_api an attribute for better reuse

---

django_freeradius/base/admin.py

"and not change" is removed because the condition change is already being tested on line 299. 
This is redundant and removing it improves code quality.
Tests pass, although `./runflake8` complains about unrelated errors in `settings.py`.

[admin] Remove redundant condition check

---

django_freeradius/base/models.py
docs/source/general/abstract_models.rst

In python3 all strings (str) are unicode string, there is no unicode decorator needed so removed all the occurrences of of the python_2_unicode_compatible decorator, solves #181

[models] Remove python_2_unicode_compatible

---

django_freeradius/settings.py
docs/source/general/importing_users.rst

Changes DJANGO_FREERADIUS_BATCH_MAIL_SENDER from "testing@localhost" to DEFAULT_FROM_EMAIL from the Django docs. 
DEFAULT_FROM_EMAIL is equal to "webmaster@localhost". 
Instead of setting the value directly, I chose to use this variable because it will be changed dynamically in the future.
Closes #179

[settings] Improve default for batch mail sender #179

---

django_freeradius/api/views.py
django_freeradius/tests/base/test_api.py

Tests works fine if the authorization header is in the standard format `Authorization: <Type> <Credentials>` but would fail if there is no space in between type and credentials.
Fixes #182

[api] Improve robustness of TokenAuthentication #182

---

django_freeradius/tests/__init__.py
django_freeradius/tests/base/test_admin.py
django_freeradius/tests/base/test_models.py

GCI task: https://codein.withgoogle.com/dashboard/task-instances/5070054078021632/

[QA] Increasing test coverage to 100% #186

---

requirements-test.txt

Install `flake8` and `isort` via `openwisp-utils[qa]`.

[qa] Install flake8 and isort via openwisp-utils[qa]

---

django_freeradius/api/views.py
django_freeradius/settings.py
django_freeradius/tests/test_api.py
docs/source/general/settings.rst
tests/settings.py

for accounting instance when saved from API
The groupname is of the group with the highest priority related to the user
Fixes #185

[accounting API] automatically fill in groupname 

---

docs/source/general/management_commands.rst
docs/source/general/setup.rst

A suggestion is made in the setup page to automate the usage of the management commands. A sample crontab is also added.

[docs] Add management commands suggestion in the setup page #171

---

docs/source/general/freeradius.rst

The docs currently assume that the user is running the django-freeradius server in the background. Since the docs did not have any instances of pointing that, this commit will make the doc mention clearly the need to keep the django-freeradius server running in the background while attempting to start the freeradius server with the config changes specified in the docs. Fixes #223

[docs] Specifies user to keep the django server running #223

---

.travis.yml

This pull request removes reference to deprecated Travis CI `sudo: true`, as per https://config.travis-ci.com/explore.
Google Code-in Link: https://codein.withgoogle.com/dashboard/task-instances/4534193363615744/
This is Code-in user aaPle.

[ci] Remove deprecated Travis key

---

requirements-test.txt

The coveralls package already has a dependency on coverage
and sets the boundary according to its support for the coverage library.
We should not duplicate this information.

[ci] Implicitly get coverage version from coverage

---

django_freeradius/templates/django_freeradius/prefix_pdf.html
django_freeradius/utils.py
requirements.txt

PR for improvement commit, which makes a migration from html2pdf to weasyprint. Changes:
- Adds `weasyprint>=44` to requirements.txt instead of `xmtml2pdf`
- Changes `STATIC_URL` in tests/settings.py to compatible with weasyprint
- Creates `BATCH_PDF_TEMPLATE_BASE_URL` in django_freeradius/settings.py
- Changes `generate_pdf` function in django_freeradius/utils.py, now it works using weasyprint API
Closes #243

[Improvement] Migrate html2pdf to weasyprint

---

docs/source/general/setup.rst

This is a PR for commit which adds links to additional info about installation of WeasyPrint for different OS to `Install stable version from pypi`, `Install development version` and `Installing for development` sections of `setup.rst`.
- Create a section for WeasyPrint installation and link to this section in each installation variant
Please mention if some other enchancements / variants should be implemented
Fixes #261

[docs] Add step to install Weasy Print #261

---

docs/source/general/contributing.rst

Org Contribution Guidelines were missing from Project Guidelines Page. Added that, restructured some content and removed duplicate/redundant information. Also added a link to the Org Contribution Guideline Page
Fixes #255

Added Org Contribution Guidelines to Project Contribution Page #255
